// Image exports with error handling
import PwkLogoImg from './pwklogo.jpg';
import GrizzyImg from './Grizzy.jpg';
import ShirazImg from './Shiraz.jpg';
import MurshidImg from './Murshid.jpg';
import AbinImg from './Abin.jpg';
import AlexImg from './Alex.jpg';
import SohalImg from './Sohal.jpg';
import FebinImg from './Febin.jpg';
import SheheerImg from './Sheheer.jpg';
import AbhiImg from './Abhi.jpg';
import AnvarImg from './Anvar.jpg';
import SreejithImg from './Sreejith.jpg';
import SulthanImg from './Sulthan.jpg';
import AsafImg from './Asaf.jpg';
import RizwanImg from './Rizwan.jpg';
import AlenImg from './Alen.jpg';
import AthulVokImg from './AthulVok.jpg';
import AdhiImg from './Adhi.jpg';
import JibinImg from './Jibin.jpg';
import PrinceImg from './Prince.jpg';
import MirfashImg from './Mirfash.jpg';
import AthulPDImg from './AthulPD.jpg';
import SubinImg from './Subin.jpg';
import BeeImg from './Bee.jpg';
import EbbieImg from './Ebbie.jpg';
import GokulImg from './Gokul.jpg';
import JujuImg from './Juju.jpg';
import KoseImg from './Kose.jpg';
import NeerajImg from './Neeraj.jpg';
import SarathImg from './Sarath.jpg';
import VarunImg from './Varun.jpg';
import ZidanImg from './Zidan.jpg';
import HariImg from './Hari.png';
import UnniImg from './Unni.jpg';
import AjinImg from './Ajin.jpg';
import VizImg from './Viz.jpg';
import ManuImg from './Manu.jpg';
import HarisImg from './Haris.jpg';
import AkshayImg from './Akshay.jpg';
import AcchuzImg from './Acchooz.jpg';
import NizamImg from './Nizam.jpg';
import SreenathImg from './Sreenath.png';
import SyamImg from './Syam.jpg';
import DistWinnersImg from './DistWinners.png';
import DistRunnersImg from './DistRunners.png';
import DistThirdImg from './DistThird.png';
import news1Img from './news1.jpg';

// Export with fallback handling
export const PwkLogo = PwkLogoImg;
export const Grizzy = GrizzyImg;
export const Shiraz = ShirazImg;
export const Murshid = MurshidImg;
export const Abin = AbinImg;
export const Alex = AlexImg;
export const Sohal = SohalImg;
export const Febin = FebinImg;
export const Sheheer = SheheerImg;
export const Abhi = AbhiImg;
export const Anvar = AnvarImg;
export const Sreejith = SreejithImg;
export const Sulthan = SulthanImg;
export const Asaf = AsafImg;
export const Rizwan = RizwanImg;
export const Alen = AlenImg;
export const AthulVok = AthulVokImg;
export const Adhi = AdhiImg;
export const Jibin = JibinImg;
export const Prince = PrinceImg;
export const Mirfash = MirfashImg;
export const AthulPD = AthulPDImg;
export const Subin = SubinImg;
export const Bee = BeeImg;
export const Ebbie = EbbieImg;
export const Gokul = GokulImg;
export const Juju = JujuImg;
export const Kose = KoseImg;
export const Neeraj = NeerajImg;
export const Sarath = SarathImg;
export const Varun = VarunImg;
export const Zidan = ZidanImg;
export const Hari = HariImg;
export const Unni = UnniImg;
export const Ajin = AjinImg;
export const Viz = VizImg;
export const Manu = ManuImg;
export const Haris = HarisImg;
export const Akshay = AkshayImg;
export const Acchuz = AcchuzImg;
export const Nizam = NizamImg;
export const Sreenath = SreenathImg;
export const Syam = SyamImg;
export const DistWinners = DistWinnersImg;
export const DistRunners = DistRunnersImg;
export const DistThird = DistThirdImg;
export const News1 = news1Img;

